name: copyparty
services:
  copyparty:
    image: copyparty/ac:latest
    container_name: copyparty
    ports:
      - 3923:3923
    volumes:
      - /DATA/AppData/$AppID/copyparty/conf:/cfg/config.conf:ro
      - /DATA/AppData/$AppID/copyparty/db:/cfg/hists #database files
      - /DATA/AppData/$AppID/media:/media #files being exposed to copyparty
#      - /DATA/AppData/$AppID/data:/downloads
    restart: unless-stopped
    