################################### QBITTORRENT STACK ###################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
#      - WEBUI_PORT=3080  # PORT WILL BE ADDED in GLUETUN PORTS
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /DATA/AppData/$AppID/data:/downloads # Map the data directory.
#    ports:
#      - 8080:8080
#      - 6881:6881
#      - 6881:6881/udp
    restart: unless-stopped
########################################################################################