################################### QBITTORRENT STACK ###################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
#      - WEBUI_PORT=3080  # PORT WILL BE ADDED in GLUETUN PORTS
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /DATA/AppData/$AppID/data:/downloads # Map the data directory.
#    ports:
#      - 8080:8080
#      - 6881:6881
#      - 6881:6881/udp
    restart: unless-stopped
########################################################################################
# CASAOS ENVIRONMENT VARIABLES AND METADATA     
    x-casaos:
      envs:
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - amd64
  # Main service for this application
  main: QBITTORRENT
  # Detailed description for the application
  description:
    en_us: Download client for your Arr Stack
  # Brief tagline for the application
  tagline:
    en_us: ARR STACK DOWNLOADER
  # Developer's information
  developer: NOOBTESTER  
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/qbittorrent.png
  title:
    en_us: QBITTORENT
  category: NoobTester
  