#This compose file adds draw.io to your stack
name: drawio
services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    ports:
      - 8180:8080
      - 8183:8443
    environment:
      PUBLIC_DNS: domain
      ORGANISATION_UNIT: unit
      ORGANISATION: org
      CITY: city
      STATE: state
      COUNTRY_CODE: country
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s

# CASAOS ENVIRONMENT VARIABLES AND METADATA     

x-casaos:
  architectures:
    - amd64
  main: drawio
  description:
    en_us: draw.io is a whiteboarding / diagramming software application..
  developer: David Benson
  
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/draw-io.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Title for the application
  title:
    en_us: draw.io
  # Category under which the application falls
  category: Personal Apps
  tagline:
    en_us: Diagram your homelab!